language: ruby
rvm:
 - 2.2.0
sudo: false
script: bundle exec rake deploy
env:
 global:
  secure: ZgmmoIuyxIMuSZxUAGYelb8INjlTbxaNjDcz0m5T0Je+yTo1IX/v3AwF6ZF9kfc/NOX5yJn5puZpyGo4YN/i3LKqtioTJRPJrr4wLQixm5SD1x7HRoknaYBJ9+3oBx49LklkICuNqg90WDdmYWX7b0aily3Ir2wQIyQHxJCsQ7kp/wxKt0rBj3H8xae5gj18W0ZdPpRpLg68r5k5Odr2e8D+4c3CgzlX1xyAuKWBn1gvSS36cBniO6XeVDiknF2FO5FDirDPWP9BHRH5hPF0XS4O36CFax1G/N2fwzm/cU9aOYjUO77sAnNg1hU8GPZG2LTP4woVTeKTnB7zY09RC6VTHVkqT3HPviIgAivdO9YwHnDHpr4TyIcUhUqnNrnbYfPnHQOu4wfg5Rd29Tf9KPH+YmVK6pphBEhScfsG0AyeWs5mULUHgOCpi6BRX3W60VACpdR/gTRpjHMIUKgzZngEDWZOphdDAfP0GrOWCnajmO/8so1MHcsyD+04hxiPSnxSLqb79ql5T8hty5dzc0ByRKuXvEq0B6QbME6DWs30yWLnGbdTo2S5ff8FGb3rpFayVH4uFuCMRLb+iVlpKk2ujr88edmGDVZgPPrMVx7bAZ913npUsdEtQO8bQHLztGKg3YHUPhHv5hMEr9trCjsOFyVxy3LVuvU1WGmeAkU=
